MAC_UNROLL_FACTOR_list="1 2 4 8 16 32 64 128 256"
Z_DIM2_CYCLIC_ENABLE_list="0 1"

for MAC_UNROLL_FACTOR in ${MAC_UNROLL_FACTOR_list}
do 
	for Z_DIM2_CYCLIC_ENABLE in ${Z_DIM2_CYCLIC_ENABLE_list}
	do
		version="${MAC_UNROLL_FACTOR}_${Z_DIM2_CYCLIC_ENABLE}"
		vitis_hls FFilter.tcl ${MAC_UNROLL_FACTOR} ${Z_DIM2_CYCLIC_ENABLE}
	done
done
